
apiVersion: storage.azure.upbound.io/v1beta1
kind: Account
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1beta1/blob
  labels:
    testing.upbound.io/example-name: example
  name: upteststorageacc
spec:
  providerConfigRef:
    name: azure

  forProvider:
    accountReplicationType: LRS
    accountTier: Standard
    location: northeurope
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example-storage-blob

