apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: kafka-example
spec:
  providerConfigRef:
    name: helm-provider
  forProvider:
    chart:
      name: kafka
      repository: https://charts.bitnami.com/bitnami
#      version: 15.2.5 ## To use devlopment versions, set ">0.0.0-0"
    namespace: kafka
    values:
      replicas: 1

