apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: kafka.acme.example.org
spec:
  connectionSecretKeys:
    - kubeconfig
  group: acme.example.org
  names:
    # 
    kind:     kafka
    plural:   kafka 
    singular: kafka
      #claimNames:
      #  kind:     kafkans
      #  singular: kafkans
      #  plural:   kafkans
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          descrition: A simple Kafka Cluster
          type: object
          properties:
            spec:
              type: object
              properties:
                anzahl:
                  type: integer
                  description: replicas of kafka
                  default: 1
              required:
                - anzahl
