apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  #https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: erkans.linsenraum.de
spec:
  group: linsenraum.de
  # LIST of versions supported by this CustomResourceDefinition
  # Sprich hier wäre ein Array mit allen bekannten Versionen!!!eins11
  versions:
  - name: v1
    # wenn serve true via API verfügbar
    served: true  
    # 
    storage: true
    # Template für die CRD
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              hiob:
                type: string
              botschaft:
                type: integer
  scope: Namespaced
  names:
    plural: erkans
    # singular name to be used as an alias on the CLI and for display
    singular: erkan
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Erkan
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - er
