# https://raw.githubusercontent.com/upbound/provider-azure/main/examples/storage/blob.yaml
apiVersion: storage.azure.upbound.io/v1beta1
kind: Blob
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1beta1/blob
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  providerConfigRef:
    name: azure

  forProvider:
    sourceContent: inline content for this blob
    storageAccountNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    storageContainerNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    type: Block

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1beta1/blob
  labels:
    testing.upbound.io/example-name: example-storage-blob
  name: linsenraum.de
spec:
  providerConfigRef:
    name: azure
  forProvider:
    location: northeurope

---

apiVersion: storage.azure.upbound.io/v1beta1
kind: Account
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1beta1/blob
  labels:
    testing.upbound.io/example-name: example
  name: upteststorageacc
spec:
  providerConfigRef:
    name: azure

  forProvider:
    accountReplicationType: LRS
    accountTier: Standard
    location: northeurope
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example-storage-blob

---

apiVersion: storage.azure.upbound.io/v1beta1
kind: Container
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1beta1/blob
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  providerConfigRef:
    name: azure

  forProvider:
    containerAccessType: private
    storageAccountNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
