#apiVersion: v1
#kind: Secret
#metadata:
#  namespace: crossplane-system
#  name: provider-do-secret
#type: Opaque
#data:
#  token: BASE64ENCODED_PROVIDER_CREDS
---
apiVersion: do.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: digitalocean
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: provider-do-secret
      key: token
