apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: kubernetes-provider-pod
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Pod
      metadata:
        # name in manifest is optional and defaults to Object name
        # name: some-other-name
        namespace: default
        labels:
          example: "true"
      spec:
        containers:
        - name: jo
          image: erkules/nginxhostname:v1
  providerConfigRef:
    name: kubernetes-provider
