apiVersion: storage.azure.crossplane.io/v1alpha3
kind: Account
metadata:
  ##make sure the length is less 24 char
  name: foxutechstoragexplane
spec:
  resourceGroupName: rg-crossplane
  storageAccountSpec:
    kind: Storage
    location: eastus
    sku:
      name: Standard_LRS
  writeConnectionSecretToRef:
    namespace: default
    name: storageaccount-connection-secret 
